### ISSUE TITLE
add health check to be coool

### ISSUE THREAD

**Issue by lukasjoc** [beuluis/owncloud#2]
https://github.com/beuluis/owncloud/blob/29fd64e6c1ba026acc65ced1dded324c4bdc8100/docker-compose.yml#L4
```yml
healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
```
